### ISSUE TITLE
Feature Request: nodejs support

### ISSUE THREAD

**Issue by antoinevg** [bendyworks/conwip-modules#1]
It would be truly cool if this was extended to add support for nodejs as well as the browser.

**Comment by spinningtopsofdoom** [comment]
I'm looking into it, the main blocker is Google Closure Library module loader is assuming a browser environment not a server environment.

**Comment by spinningtopsofdoom** [comment]
After digging into this for a few days I believe that this is not feasible with the current version of the Closure Compiler.

Google Closure module loading works the following way

- Get all the uris (in dependecy order) for a given module
- Retrieve the raw JavaScript (text) of all the files pointed to via the uris
- Load the JavaScript into the global scope through the `eval` function

Node primarily works with module scope which is incompatible with using `eval` to load JavaScript into the global scope.

To get dynamic modules working for Node each module would need to correctly import it's dependencies and export all variables it created. See this Google Closure issue for more details https://github.com/google/closure-compiler/issues/2406

I'll update the readme to include this information then close this issue.

Let me know if theres any part of my explanation where I need to clarify or go into more detail.

**Comment by antoinevg** [comment]
Ouch, I had no idea Closure modules exist in the global scope.

That's a great explanation and gives me a much better idea of why Clojurescript is such a disaster area when it comes to any kind of runtime module loading support.

Thank you.

**Comment by jiangts** [comment]
Curious -- why would Node.js need Closure Modules support?
Isn't the main point of modules to reduce code size, which isn't so relevant on the server side?

**Comment by antoinevg** [comment]
The main point of modules is to allow runtime dependency resolution. 

Reducing code size is only one application of such a feature.

Writing an app that can load plugins developed by others is another application.

Both Clojure & Clojurescript do really badly when it comes to this.

**Comment by spinningtopsofdoom** [comment]
The documentation explaining why Node Support is not feasible has been added in commit 03207f2c0b1e37b6fbbf015df031da5853c95f93
