### ISSUE TITLE
Project does not show up when searching for "code splitting"

### ISSUE THREAD

**Issue by claudiuapetrei** [bendyworks/conwip-modules#2]
Hi,

Really awesome work. Just about to start working on implementing module loading on my new project.

Im coming from js/webpack/python land. Maybe that's why, but I was just google-ing "clojurescript code splitting".  It seems like other people use the term https://goo.gl/YqD68n. 

Luckily for me I saw your awesome talk at clojure-west on youtube.

Would be great if you could include "code splitting" in the readme/project name etc... so that it shows up on google searches.

For beginners like me clojurescript when doing research what shows up for 'code splitting' is a bit of a red flag (given how easy it is with webpack).

**Comment by spinningtopsofdoom** [comment]
I can add that to the README along with a link to my talk. I'm not as familiar as to what "code splitting" means from a webpack perspective, could you give me around 3 concrete examples of webpack code splitting so my documentation will be accurate?

**Comment by claudiuapetrei** [comment]
@spinningtopsofdoom Sure. 

Webpack docs: https://webpack.js.org/guides/code-splitting-async/
React router: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/code-splitting.md
Medium article: https://medium.com/@apostolos/server-side-rendering-code-splitting-and-hot-reloading-with-react-router-v4-87239cfc172c

**Comment by spinningtopsofdoom** [comment]
I've added documentation detailing ClojureScript code splitting and how it differs from webpack in commit 45e2b124c6cf7836322a0d158967f2f763182f08
